sensor_kit_base_link:
  lexus3/duro:
    x: 1.6
    y: 0.0
    z: 0.2
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lexus3/gps:
    x: 1.542
    y: 0.49
    z: 1.479
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lexus3/_left_camera_frame:
    x: 1.6
    y: 0.0
    z: 1.286
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lexus3/duro_gps_imu:
    x: 0.0
    y: 0.0
    z: 0.2
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lexus3/ground_link:
    x: 0.0
    y: 0.0
    z: -0.37
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lexus3/os_left_a:
    x: 0.75
    y: 0.5
    z: 1.3
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lexus3/os_right_a:
    x: 1.53
    y: -0.5
    z: 1.41
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lexus3/os_center_a:
    x: 0.75
    y: 0.0
    z: 1.91
    roll: 0.0
    pitch: 0.0
    yaw: 0.0